# Generated by Django 3.1.2 on 2020-11-08 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=50)),
                ('stripe_id', models.CharField(blank=True, max_length=255)),
                ('cloud_lines_account', models.CharField(blank=True, max_length=100)),
                ('enabled', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('admins', models.ManyToManyField(blank=True, related_name='admins', to=settings.AUTH_USER_MODEL, verbose_name='Admins')),
                ('members', models.ManyToManyField(blank=True, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='Memberships')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('member', 'Member'), ('complimentry', 'Complimentry'), ('donor', 'Donor')], default='member', help_text='Type of member', max_length=12, null=True)),
                ('status', models.CharField(choices=[('archive', 'Archive'), ('dead', 'Dead'), ('live', 'Live'), ('resigned', 'Resigned')], default='live', help_text='Current status', max_length=10, null=True)),
                ('membership_number', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('member', 'Member'), ('joint_members', 'Joint Members'), ('friend', 'Friend'), ('joint_friend', 'Joint Friend'), ('corporate', 'Corporate'), ('life_member', 'Life Member'), ('overseas_supplement', 'Overseas Supplement'), ('junior', 'Junior'), ('teen', 'Teen'), ('governor', 'Governor')], default='member', help_text='Category of member', max_length=19, null=True)),
                ('renewal_status', models.CharField(choices=[('wrong_address', 'Wrong Address'), ('underpaying ', 'Underpaying '), ('current_member', 'Current Member'), ('first_reminder', 'First Reminder'), ('second_reminder', 'Second Reminder'), ('lapsed_no_response', 'Lapsed no response'), ('resigned', 'Resigned'), ('dead', 'Dead'), ('non_member ', 'Non member')], default='current_member', help_text='Renewal status of member', max_length=19, null=True)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('cheque ', 'Cheque '), ('standing_order', 'Standing Order'), ('caf_standing_order', 'CAF standing Order'), ('petty_cash', 'Petty Cash'), ('card_payment', 'Card Payment'), ('bacs', 'BACS'), ('caf_voucher', 'Caf Voucher'), ('postal_cheque ', 'Postal Cheque'), ('paypal', 'Paypal')], default='card_payment', help_text='Payment type used by member', max_length=19, null=True)),
                ('date_resigned', models.DateField(auto_now=True)),
                ('standing_order_amount', models.FloatField(blank=True, null=True)),
                ('standing_order_started', models.CharField(blank=True, max_length=100)),
                ('gift_aid', models.BooleanField(default=False)),
                ('signature_given_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('membership_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_package', to='membership.membershippackage', verbose_name='Membership Package')),
                ('user_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
        ),
        migrations.CreateModel(
            name='Equine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_owner', models.BooleanField(default=True)),
                ('badge', models.BooleanField(default=True)),
                ('joined', models.DateField(auto_now=True)),
                ('expired', models.DateField(blank=True, null=True)),
                ('actual_renewal', models.DateField(blank=True, null=True)),
                ('do_not_mail', models.BooleanField(default=False)),
                ('want_raffle_tickets', models.BooleanField(default=False)),
                ('overseas', models.BooleanField(default=False)),
                ('bad_address', models.BooleanField(default=False)),
                ('returned_gdpr_date', models.DateField(blank=True, null=True)),
                ('gdpr_post', models.BooleanField(default=False)),
                ('gdpr_email', models.BooleanField(default=False)),
                ('gdpr_phone', models.BooleanField(default=False)),
                ('membership_package', models.ManyToManyField(related_name='emembership_package', to='membership.MembershipPackage', verbose_name='Equine Membership Package')),
            ],
        ),
    ]
