# Generated by Django 3.1.2 on 2020-11-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='date_resigned',
        ),
        migrations.RemoveField(
            model_name='member',
            name='gift_aid',
        ),
        migrations.RemoveField(
            model_name='member',
            name='signature_given_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='standing_order_started',
        ),
        migrations.AddField(
            model_name='equine',
            name='date_resigned',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equine',
            name='gift_aid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equine',
            name='signature_given_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
