# Generated by Django 3.1.2 on 2020-11-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_equine_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippackage',
            name='bolton',
            field=models.CharField(choices=[('equine', 'Equine')], default=None, help_text='Type of member', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
