# Generated by Django 3.1.2 on 2020-11-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_auto_20201110_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershippackage',
            name='bolton',
            field=models.CharField(choices=[('none', 'None'), ('equine', 'Equine')], default=None, help_text='Type of member', max_length=12, null=True),
        ),
    ]
