# Generated by Django 3.1.2 on 2020-11-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_auto_20201110_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='email_confirm',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
