# Generated by Django 3.1.2 on 2020-11-11 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_auto_20201111_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='email_confirm',
            new_name='email_confirmation',
        ),
    ]
