# Generated by Django 3.1.2 on 2020-11-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_auto_20201111_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email_confirmation',
        ),
        migrations.AddField(
            model_name='member',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
