# Generated by Django 3.1.2 on 2020-11-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_auto_20201111_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
