# Generated by Django 3.1.2 on 2020-11-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0012_auto_20201111_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='standing_order_amount',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
