# Generated by Django 3.1.2 on 2020-11-11 21:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0013_auto_20201111_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershippackage',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL, verbose_name='Members'),
        ),
    ]
