# Generated by Django 3.1.2 on 2020-11-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0014_auto_20201111_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershippackage',
            name='bolton',
            field=models.CharField(choices=[('none', 'None'), ('equine', 'Equine')], default='none', help_text='Boltons add additional fields to your member form.', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='membershippackage',
            name='cloud_lines_account',
            field=models.CharField(blank=True, help_text='Link your membership account to your cloud-lines account', max_length=100),
        ),
        migrations.AlterField(
            model_name='membershippackage',
            name='organisation_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
