# Generated by Django 3.1.2 on 2020-11-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0017_auto_20201113_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippackage',
            name='stripe_acct_owner_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
