# Generated by Django 3.1.2 on 2020-11-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0019_auto_20201120_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershippackage',
            name='stripe_acct_owner_id',
        ),
    ]
