# Generated by Django 3.1.2 on 2020-11-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0020_remove_membershippackage_stripe_acct_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippackage',
            name='stripe_owner_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
