# Generated by Django 3.1.2 on 2020-11-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0021_membershippackage_stripe_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
