# Generated by Django 3.1.2 on 2020-11-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0022_member_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippackage',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
