# Generated by Django 3.1.2 on 2020-11-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0023_membershippackage_stripe_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippackage',
            name='membership_price_per_month',
            field=models.IntegerField(default=0.0, help_text='Price in £ per month'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershippackage',
            name='membership_price_per_year',
            field=models.IntegerField(default=0.0, help_text='Price in £ per year'),
            preserve_default=False,
        ),
    ]
