# Generated by Django 3.1.2 on 2020-11-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0026_auto_20201128_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
