# Generated by Django 3.1.2 on 2020-11-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0027_member_stripe_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='payment_type',
            field=models.CharField(choices=[('card_payment', 'Card Payment'), ('cash', 'Cash'), ('cheque', 'Cheque '), ('standing_order', 'Standing Order'), ('caf_standing_order', 'CAF standing Order'), ('petty_cash', 'Petty Cash'), ('bacs', 'BACS'), ('caf_voucher', 'Caf Voucher'), ('postal_cheque ', 'Postal Cheque'), ('paypal', 'Paypal')], default='Card Payment', help_text='Payment type used by member', max_length=19, null=True),
        ),
    ]
