# Generated by Django 3.1.2 on 2020-12-04 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0028_auto_20201129_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equine',
            name='membership_package',
        ),
        migrations.AddField(
            model_name='equine',
            name='membership_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emembership_package', to='membership.membershippackage', verbose_name='Equine Membership Package'),
        ),
    ]
