# Generated by Django 3.1.2 on 2020-12-06 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0029_auto_20201204_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='renewal_status',
        ),
    ]
