# Generated by Django 3.1.2 on 2020-12-08 22:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0030_remove_member_renewal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='status',
        ),
        migrations.AddField(
            model_name='member',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='payment_type',
            field=models.CharField(choices=[('card_payment', 'Card Payment'), ('cash', 'Cash'), ('cheque', 'Cheque '), ('standing_order', 'Standing Order'), ('caf_standing_order', 'CAF standing Order'), ('petty_cash', 'Petty Cash'), ('bacs', 'BACS'), ('caf_voucher', 'Caf Voucher'), ('postal_cheque ', 'Postal Cheque'), ('paypal', 'Paypal')], default='card_payment', help_text='Payment type used by member', max_length=19, null=True),
        ),
    ]
