# Generated by Django 3.1.2 on 2020-12-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0031_auto_20201208_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
