# Generated by Django 3.1.2 on 2020-12-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0033_auto_20201213_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershippackage',
            name='membership_price_per_month',
            field=models.DecimalField(decimal_places=2, help_text='Price in £ per month', max_digits=5, verbose_name='Membership Price Per Month'),
        ),
        migrations.AlterField(
            model_name='membershippackage',
            name='membership_price_per_year',
            field=models.DecimalField(decimal_places=2, help_text='Price in £ per year', max_digits=5, verbose_name='Membership Price Per Year'),
        ),
    ]
