# Generated by Django 3.1.2 on 2020-12-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0034_auto_20201222_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
