# Generated by Django 3.1.2 on 2020-12-29 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0036_auto_20201224_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='billing_period',
        ),
        migrations.RemoveField(
            model_name='member',
            name='category',
        ),
        migrations.RemoveField(
            model_name='member',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='member',
            name='created',
        ),
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='membership_number',
        ),
        migrations.RemoveField(
            model_name='member',
            name='membership_package',
        ),
        migrations.RemoveField(
            model_name='member',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='member',
            name='record_type',
        ),
        migrations.RemoveField(
            model_name='member',
            name='stripe_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='stripe_subscription_id',
        ),
        migrations.AlterField(
            model_name='member',
            name='user_account',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MembershipSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(blank=True, max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255)),
                ('record_type', models.CharField(choices=[('member', 'Member'), ('complimentry', 'Complimentry'), ('donor', 'Donor')], default='member', help_text='Type of member', max_length=12, null=True)),
                ('membership_number', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('member', 'Member'), ('joint_members', 'Joint Members'), ('friend', 'Friend'), ('joint_friend', 'Joint Friend'), ('corporate', 'Corporate'), ('life_member', 'Life Member'), ('overseas_supplement', 'Overseas Supplement'), ('junior', 'Junior'), ('teen', 'Teen'), ('governor', 'Governor')], default='member', help_text='Category of member', max_length=19, null=True)),
                ('payment_type', models.CharField(choices=[('card_payment', 'Card Payment'), ('cash', 'Cash'), ('cheque', 'Cheque '), ('standing_order', 'Standing Order'), ('caf_standing_order', 'CAF standing Order'), ('petty_cash', 'Petty Cash'), ('bacs', 'BACS'), ('caf_voucher', 'Caf Voucher'), ('postal_cheque ', 'Postal Cheque'), ('paypal', 'Paypal')], default='card_payment', help_text='Payment type used by member', max_length=19, null=True)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly ')], default='monthly', help_text='Payment frequency', max_length=19, null=True)),
                ('comments', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='membership.member', verbose_name='Membership Subscription')),
                ('membership_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_package', to='membership.membershippackage', verbose_name='Membership Package')),
            ],
        ),
    ]
