# Generated by Django 3.1.2 on 2020-12-30 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0038_membershipsubscription_validated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equine',
            name='member',
        ),
        migrations.RemoveField(
            model_name='membershippackage',
            name='members',
        ),
        migrations.AddField(
            model_name='equine',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esub', to='membership.membershipsubscription', verbose_name='Equine Subscription'),
        ),
    ]
