# Generated by Django 3.1.4 on 2021-01-04 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0039_auto_20201230_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('stripe_id', models.CharField(blank=True, max_length=255)),
                ('validated', models.BooleanField(default=False)),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Donator', to=settings.AUTH_USER_MODEL, verbose_name='Donator')),
            ],
        ),
    ]
