# Generated by Django 3.1.2 on 2021-01-02 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0040_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipsubscription',
            name='membership_number',
        ),
    ]
