# Generated by Django 3.1.2 on 2021-01-03 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0041_remove_membershipsubscription_membership_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipsubscription',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='membership.member', verbose_name='Membership Subscription'),
        ),
        migrations.AlterField(
            model_name='membershipsubscription',
            name='membership_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_package', to='membership.membershippackage', verbose_name='Membership Package'),
        ),
    ]
