# Generated by Django 3.1.2 on 2021-01-03 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0042_auto_20210103_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='organisation_name',
        ),
        migrations.AddField(
            model_name='donation',
            name='membership_package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dmembership_package', to='membership.membershippackage', verbose_name='Membership Package'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='donator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaton', to=settings.AUTH_USER_MODEL, verbose_name='Donator'),
        ),
    ]
