# Generated by Django 3.1.2 on 2021-01-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0043_auto_20210103_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='amount',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
    ]
