# Generated by Django 3.1.2 on 2021-01-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0045_auto_20210103_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershippackage',
            name='membership_price_per_month',
        ),
        migrations.RemoveField(
            model_name='membershippackage',
            name='membership_price_per_month_id',
        ),
        migrations.RemoveField(
            model_name='membershippackage',
            name='membership_price_per_year',
        ),
        migrations.RemoveField(
            model_name='membershippackage',
            name='membership_price_per_year_id',
        ),
    ]
