# Generated by Django 3.1.2 on 2021-01-03 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0046_auto_20210103_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipsubscription',
            name='category',
        ),
        migrations.RemoveField(
            model_name='membershipsubscription',
            name='record_type',
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_price_id', models.CharField(blank=True, max_length=255)),
                ('nickname', models.CharField(blank=True, max_length=255)),
                ('interval', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly ')], default='monthly', help_text='Payment frequency', max_length=19, null=True)),
                ('amount', models.CharField(blank=True, max_length=255)),
                ('membership_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pmembership_package', to='membership.membershippackage', verbose_name='Membership Package')),
            ],
        ),
    ]
