# Generated by Django 3.1.2 on 2021-01-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0047_auto_20210103_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
