# Generated by Django 3.1.2 on 2021-01-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0048_price_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='interval',
            field=models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly ')], default='monthly', help_text='Payment frequency', max_length=19, null=True),
        ),
    ]
