# Generated by Django 3.1.2 on 2021-01-04 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0049_auto_20210103_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipsubscription',
            name='billing_period',
        ),
        migrations.AddField(
            model_name='membershipsubscription',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price', to='membership.price', verbose_name='Price'),
        ),
    ]
