# Generated by Django 3.1.2 on 2021-01-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0051_auto_20210104_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipsubscription',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
