# Generated by Django 3.1.4 on 2021-01-05 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0052_membershipsubscription_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='equine',
            name='member_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.member'),
        ),
    ]
