# Generated by Django 3.1.4 on 2021-01-05 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0053_equine_member_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equine',
            name='member_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.member'),
        ),
    ]
