# Generated by Django 3.1.2 on 2021-01-09 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0053_membershippackage_business_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipsubscription',
            name='payment_type',
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_name', models.CharField(max_length=250)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque '), ('standing_order', 'Standing Order'), ('caf_standing_order', 'CAF standing Order'), ('petty_cash', 'Petty Cash'), ('bacs', 'BACS'), ('caf_voucher', 'Caf Voucher'), ('postal_cheque ', 'Postal Cheque'), ('paypal', 'Paypal')], default='card_payment', help_text='Payment type used by member', max_length=19, null=True)),
                ('information', models.TextField(blank=True)),
                ('active', models.BooleanField(default=False)),
                ('membership_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pmmembership_package', to='membership.membershippackage', verbose_name='Membership Package')),
            ],
        ),
    ]
