# Generated by Django 3.1.4 on 2021-01-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0054_auto_20210105_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equine',
            name='member_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
