# Generated by Django 3.1.2 on 2021-01-09 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0054_auto_20210109_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='payment_type',
        ),
    ]
