# Generated by Django 3.1.4 on 2021-01-05 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0055_auto_20210105_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equine',
            name='member_name',
        ),
    ]
