# Generated by Django 3.1.2 on 2021-01-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0057_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipsubscription',
            name='membership_expiry',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='membershipsubscription',
            name='membership_start',
            field=models.DateField(auto_now=True),
        ),
    ]
