# Generated by Django 3.1.2 on 2021-01-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0058_auto_20210110_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipsubscription',
            name='membership_start',
            field=models.DateField(null=True),
        ),
    ]
