# Generated by Django 3.1.2 on 2021-01-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0059_auto_20210110_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equine',
            name='actual_renewal',
        ),
        migrations.RemoveField(
            model_name='equine',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='equine',
            name='joined',
        ),
        migrations.AlterField(
            model_name='equine',
            name='date_resigned',
            field=models.DateField(blank=True),
        ),
    ]
