# Generated by Django 3.1.2 on 2021-01-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0060_auto_20210110_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equine',
            name='date_resigned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equine',
            name='returned_gdpr_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='equine',
            name='signature_given_date',
            field=models.DateField(null=True),
        ),
    ]
