# Generated by Django 3.1.4 on 2021-01-11 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0062_auto_20210110_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipsubscription',
            name='membership_start',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
