# Generated by Django 3.1.2 on 2021-01-11 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0063_auto_20210111_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershipsubscription',
            old_name='membership_start',
            new_name='membership_start_old',
        ),
    ]
