# Generated by Django 3.1.2 on 2021-01-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0064_auto_20210111_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipsubscription',
            name='membership_start',
            field=models.DateField(null=True),
        ),
    ]
