# Generated by Django 3.1.2 on 2021-01-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0065_membershipsubscription_membership_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipsubscription',
            name='membership_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membershipsubscription',
            name='membership_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
