# Generated by Django 3.1.2 on 2021-01-11 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0066_auto_20210111_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipsubscription',
            name='membership_start_old',
        ),
    ]
