# Generated by Django 3.1.4 on 2021-01-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0067_remove_membershipsubscription_membership_start_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='visible_to_users',
            field=models.BooleanField(default=True),
        ),
    ]
