# Generated by Django 3.1.2 on 2021-01-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0067_remove_membershipsubscription_membership_start_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='equine',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equine',
            name='date_entered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equine',
            name='date_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equine',
            name='do_not_mail_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equine',
            name='fk_renewal_status',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='equine',
            name='mail_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equine',
            name='returned_gdpr_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equine',
            name='signature_given_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
