# Generated by Django 3.1.4 on 2021-01-12 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0068_price_visible_to_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='visible_to_users',
            new_name='visible',
        ),
    ]
