# Generated by Django 3.1.2 on 2021-01-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0069_auto_20210113_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equine',
            old_name='animal_owner',
            new_name='owner_breeder',
        ),
        migrations.RemoveField(
            model_name='equine',
            name='badge',
        ),
        migrations.AddField(
            model_name='equine',
            name='donor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equine',
            name='office_telephone',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='equine',
            name='source',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
