# Generated by Django 3.1.2 on 2021-01-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0070_auto_20210113_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='equine',
            name='volunteer',
            field=models.BooleanField(default=False),
        ),
    ]
