# Generated by Django 3.1.2 on 2021-01-13 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0071_equine_volunteer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equine',
            old_name='want_raffle_tickets',
            new_name='no_raffle_tickets',
        ),
    ]
