# Generated by Django 3.1.2 on 2021-01-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0073_auto_20210113_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equine',
            old_name='gift_aid',
            new_name='gift_aid_decision',
        ),
        migrations.AddField(
            model_name='equine',
            name='gift_aid_decision_made_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equine',
            name='gift_aid_signature',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='equine',
            name='gift_aid_type',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
