# Generated by Django 3.1.2 on 2021-01-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0074_auto_20210113_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='equine',
            name='contact_via_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equine',
            name='contact_via_email_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
