# Generated by Django 3.1.2 on 2021-01-13 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0075_auto_20210113_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equine',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='equine',
            name='bank_address',
        ),
        migrations.RemoveField(
            model_name='equine',
            name='bank_sort_code',
        ),
    ]
