# Generated by Django 3.1.4 on 2021-01-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0076_auto_20210113_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
