# Generated by Django 3.1.2 on 2021-01-14 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0069_auto_20210112_1315'),
        ('membership', '0077_paymentmethod_visible'),
    ]

    operations = [
    ]
