# Generated by Django 3.1.2 on 2021-01-15 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0079_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='membership.membershipsubscription', verbose_name='Subscription Payment'),
        ),
    ]
