# Generated by Django 3.1.2 on 2021-01-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0080_auto_20210115_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gift_aid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='gift_aid_percentage',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
