# Generated by Django 3.1.2 on 2021-01-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0082_auto_20210115_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipsubscription',
            name='membership_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
