# Generated by Django 3.1.2 on 2021-01-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0083_membershipsubscription_membership_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_number',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
