# Generated by Django 3.1.2 on 2021-01-17 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0084_payment_payment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_method', to='membership.paymentmethod', verbose_name='Payment Method'),
        ),
    ]
