# Generated by Django 3.1.2 on 2021-01-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0085_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
