# Generated by Django 3.1.2 on 2021-01-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0086_payment_stripe_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_payment_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
