# Generated by Django 3.1.2 on 2021-01-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0087_auto_20210118_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippackage',
            name='custom_fields',
            field=models.TextField(blank=True),
        ),
    ]
