# Generated by Django 3.1.2 on 2021-01-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0088_membershippackage_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipsubscription',
            name='custom_fields',
            field=models.TextField(blank=True),
        ),
    ]