# Generated by Django 3.1.2 on 2021-01-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0088_membershippackage_custom_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershippackage',
            name='custom_fields',
            field=models.JSONField(blank=True),
        ),
    ]
