# Generated by Django 3.1.2 on 2021-01-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0089_auto_20210124_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershippackage',
            name='custom_fields',
            field=models.TextField(blank=True),
        ),
    ]
