# Generated by Django 3.1.2 on 2021-01-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0089_membershipsubscription_custom_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipsubscription',
            name='membership_number',
            field=models.IntegerField(blank=True),
        ),
    ]
