# Generated by Django 3.1.2 on 2021-01-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0090_auto_20210124_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipsubscription',
            name='custom_fields',
            field=models.TextField(blank=True),
        ),
    ]
