# Generated by Django 3.1.2 on 2021-02-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0091_auto_20210208_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippackage',
            name='payment_reminder_email',
            field=models.TextField(blank=True),
        ),
    ]
