# Generated by Django 3.1.2 on 2021-02-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0093_auto_20210215_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipsubscription',
            name='gift_aid',
            field=models.BooleanField(default=False),
        ),
    ]
