# Generated by Django 3.1.2 on 2021-02-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0094_membershipsubscription_gift_aid'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipsubscription',
            name='last_reminder',
            field=models.DateField(blank=True, null=True),
        ),
    ]
