# Generated by Django 3.1.2 on 2021-02-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0095_membershipsubscription_last_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='gift_aid',
            field=models.BooleanField(default=False),
        ),
    ]
