# Generated by Django 3.1.2 on 2021-03-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0097_auto_20210315_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='company',
            field=models.CharField(blank=True, help_text='Company name (if a company membership)', max_length=255),
        ),
    ]
