# Generated by Django 3.1.2 on 2021-03-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0097_auto_20210315_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='interval',
            field=models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly '), ('one_off', 'One Off')], default='monthly', help_text='Payment frequency', max_length=19, null=True),
        ),
    ]
