# Generated by Django 3.1.2 on 2021-03-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0098_auto_20210317_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='interval',
            field=models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly '), ('one_time', 'One Time')], default='monthly', help_text='Payment frequency', max_length=19, null=True),
        ),
    ]
