# Generated by Django 3.1.2 on 2021-03-19 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0099_auto_20210317_1529'),
        ('membership', '0099_auto_20210317_1154'),
    ]

    operations = [
    ]
