# Generated by Django 3.1.2 on 2021-12-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0103_auto_20210330_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipsubscription',
            name='stripe_schedule_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
