# Generated by Django 3.1.2 on 2022-11-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0104_membershipsubscription_stripe_schedule_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='secondary_contact_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
