# Generated by Django 3.1.2 on 2022-11-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0105_member_secondary_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='contact_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='secondary_contact_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
