# Generated by Django 3.1.2 on 2022-11-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0106_auto_20221125_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipsubscription',
            name='stripe_payment_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
