# Generated by Django 3.1.2 on 2023-01-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0108_auto_20221205_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipsubscription',
            name='breeding_prefix',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
