# Generated by Django 3.1.2 on 2023-01-23 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0109_membershipsubscription_breeding_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipsubscription',
            name='breeding_prefix',
        ),
    ]
