# Generated by Django 3.1.2 on 2023-06-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0110_remove_membershipsubscription_breeding_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='currency',
            field=models.CharField(blank=True, default='GBP', max_length=255),
        ),
    ]
