# Generated by Django 4.2.2 on 2023-07-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0112_alter_donation_id_alter_equine_id_alter_member_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippackage',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
