# Generated by Django 4.2.2 on 2023-10-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0113_membershippackage_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipsubscription',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
