# Generated by Django 4.2.2 on 2023-12-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0115_alter_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
