# this gets a list of all the currencies that stripe supports, where the key is the three-letter ISO code, and the value is the description. The following aren't included because either they are, or stripe handles them as, zero decimal currencies:
    # 'BIF': 'Burundi Franc',
    # 'CLP': 'Chilean Peso',
    # 'DJF': 'Djibouti Franc',
    # 'GNF': 'Guinea Franc',
    # 'JPY': 'Japanese yen',
    # 'KMF': 'Comoro franc',
    # 'KRW': 'South Korean won',
    # 'MGA': 'Malagasy ariary',
    # 'PYG': 'Paraguayan guarani',
    # 'RWF': 'Rwanda franc',
    # 'UGX': 'Ugandan shilling',
    # 'VND': 'Vietnamese dong',
    # 'VUV': 'Vanuatu vatu',
    # 'XAF': 'Central African CFA franc',
    # 'XOF': 'West African CFA franc',
    # 'XPF': 'CFP franc',
    # 'HUF': 'Hungarian forint',

def get_currencies():
    return {
        #'AED': 'United Arab Emirates Dirham',
        #'AFN': 'Afghan Afghani',
        #'ALL': 'Albanian Lek',
        #'AMD': 'Armenian Dram',
        #'ANG': 'Netherlands Antillean Gulden',
        #'AOA': 'Angolan Kwanza',
        #'ARS': 'Argentine Peso',
        'AUD': 'Australian Dollar',
        #'AWG': 'Aruban Florin',
        #'AZN': 'Azerbaijani Manat',
        #'BAM': 'Bosnia & Herzegovina Convertible Mark',
        #'BBD': 'Barbadian Dollar',
        #'BDT': 'Bangladeshi Taka',
        'BGN': 'Bulgarian Lev',
        #'BMD': 'Bermudian Dollar',
        #'BND': 'Brunei Dollar',
        #'BOB': 'Bolivian Boliviano',
        #'BRL': 'Brazilian Real',
        #'BSD': 'Bahamian Dollar',
        #'BWP': 'Botswana Pula',
        #'BZD': 'Belize Dollar',
        'CAD': 'Canadian Dollar',
        #'CDF': 'Congolese Franc',
        'CHF': 'Swiss Franc',
        #'CNY': 'Chinese Renminbi Yuan',
        #'COP': 'Colombian Peso',
        #'CRC': 'Costa Rican Colón',
        #'CVE': 'Cape Verdean Escudo',
        'CZK': 'Czech Koruna',
        'DKK': 'Danish Krone',
        #'DOP': 'Dominican Peso',
        #'DZD': 'Algerian Dinar',
        #'EGP': 'Egyptian Pound',
        #'ETB': 'Ethiopian Birr',
        'EUR': 'Euro',
        #'FJD': 'Fijian Dollar',
        #'FKP': 'Falkland Islands Pound',
        'GBP': 'British Pound',
        #'GEL': 'Georgian Lari',
        #'GIP': 'Gibraltar Pound',
        #'GMD': 'Gambian Dalasi',
        #'GTQ': 'Guatemalan Quetzal',
        #'GYD': 'Guyanese Dollar',
        'HKD': 'Hong Kong Dollar',
        #'HNL': 'Honduran Lempira',
        #'HRK': 'Croatian Kuna',
        #'HTG': 'Haitian Gourde',
        #'IDR': 'Indonesian Rupiah',
        #'ILS': 'Israeli New Sheqel',
        #'INR': 'Indian Rupee',
        #'ISK': 'Icelandic Króna',
        #'JMD': 'Jamaican Dollar',
        #'KES': 'Kenyan Shilling',
        #'KGS': 'Kyrgyzstani Som',
        #'KHR': 'Cambodian Riel',
        #'KYD': 'Cayman Islands Dollar',
        #'KZT': 'Kazakhstani Tenge',
        #'LAK': 'Lao Kip',
        #'LBP': 'Lebanese Pound',
        #'LKR': 'Sri Lankan Rupee',
        #'LRD': 'Liberian Dollar',
        #'LSL': 'Lesotho Loti',
        #'MAD': 'Moroccan Dirham',
        #'MDL': 'Moldovan Leu',
        #'MKD': 'Macedonian Denar',
        #'MMK':  'Burmese Kyat',
        #'MNT': 'Mongolian Tögrög',
        #'MOP': 'Macanese Pataca',
        #'MRO': 'Mauritanian Ouguiya',
        #'MUR': 'Mauritian Rupee',
        #'MVR': 'Maldivian Rufiyaa',
        #'MWK': 'Malawian Kwacha',
        #'MXN': 'Mexican Peso',
        #'MYR': 'Malaysian Ringgit',
        #'MZN': 'Mozambican Metical',
        #'NAD': 'Namibian Dollar',
        #'NGN': 'Nigerian Naira',
        #'NIO': 'Nicaraguan Córdoba',
        'NOK': 'Norwegian Krone',
        #'NPR': 'Nepalese Rupee',
        'NZD': 'New Zealand Dollar',
        #'PAB': 'Panamanian Balboa',
        #'PEN': 'Peruvian Nuevo Sol',
        #'PGK': 'Papua New Guinean Kina',
        #'PHP': 'Philippine Peso',
        #'PKR': 'Pakistani Rupee',
        'PLN': 'Polish Złoty',
        #'QAR': 'Qatari Riyal',
        'RON': 'Romanian Leu',
        #'RSD': 'Serbian Dinar',
        #'RUB': 'Russian Ruble',
        #'SAR': 'Saudi Riyal',
        #'SBD': 'Solomon Islands Dollar',
        #'SCR': 'Seychellois Rupee',
        'SEK': 'Swedish Krona',
        'SGD': 'Singapore Dollar',
        #'SHP': 'Saint Helenian Pound',
        #'SLL': 'Sierra Leonean Leone',
        #'SOS': 'Somali Shilling',
        #'SRD': 'Surinamese Dollar',
        #'STD': 'São Tomé and Príncipe Dobra',
        #'SZL': 'Swazi Lilangeni',
        #'THB': 'Thai Baht',
        #'TJS': 'Tajikistani Somoni',
        #'TOP': 'Tongan Paʻanga',
        #'TRY': 'Turkish Lira',
        #'TTD': 'Trinidad and Tobago Dollar',
        #'TWD': 'New Taiwan Dollar',
        #'TZS': 'Tanzanian Shilling',
        #'UAH': 'Ukrainian Hryvnia',
        'USD': 'United States Dollar',
        #'UYU': 'Uruguayan Peso',
        #'UZS': 'Uzbekistani Som',
        #'WST': 'Samoan Tala',
        #'XCD': 'East Caribbean Dollar',
        #'YER': 'Yemeni Rial',
        #'ZAR': 'South African Rand',
        #'ZMW': 'Zambian Kwacha'
    }

def get_countries():
    return {
        'AU': 'Australia',
        'AT': 'Austria',
        'BE': 'Belgium',
        'BG': 'Bulgaria',
        'CA': 'Canada',
        'CY': 'Cyprus',
        'CZ': 'Czech Republic',
        'DK': 'Denmark',
        'EE': 'Estonia',
        'FI': 'Finland',
        'FR': 'France',
        'DE': 'Germany',
        'GR': 'Greece',
        'CN': 'Hong Kong SAR China',
        'IE': 'Ireland',
        'IT': 'Italy',
        'LV': 'Latvia',
        'LT': 'Lithuania',
        'LU': 'Luxembourg',
        'MT': 'Malta',
        'NL': 'Netherlands',
        'NZ': 'New Zealand',
        'NO': 'Norway',
        'PL': 'Poland',
        'PT': 'Portugal',
        'RO': 'Romania',
        'SG': 'Singapore',
        'SK': 'Slovakia',
        'SI': 'Slovenia',
        'ES': 'Spain',
        'SE': 'Sweden',
        'CH': 'Switzerland',
        'GB': 'United Kingdom',
        'US': 'United States'
    }
